version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=megasecret
      - MYSQL_DATABASE=ecomap
